---
- name: Print system facts
  hosts: all
  tasks:
    - name: Print OS name
      debug:
        var: ansible_distribution

    - name: Print SELinux mode
      debug:
        var: ansible_selinux.mode

    - name: Print RAM (free memory in MB)
      debug:
        var: ansible_memory_mb.real.free

    - name: Print Processor name
      debug:
        var: ansible_processor[2]
