---
- name: Understanding vars and facts
  hosts: all
  become: yes
  gather_facts: False
  vars:
    USRNM: playuser
    COMM: variable from playbook

  tasks:
    - name: Create user
      ansible.builtin.user:
        name: "{{ USRNM }}"
        comment: "{{ COMM }}"
      register: usrout

    - debug:
        var: usrout.name

    - debug:
        var: usrout.comment
